function createfiguretask(g1)
%CREATEFIGURE(g1)
%  G1:  图形或有向图对象

%  由 MATLAB 于 21-Apr-2024 15:04:50 自动生成

% 创建 figure
figure1 = figure;

% 创建 axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');
[n,m] = size(g1.Nodes);
% 创建 plot
plot(g1,'Parent',axes1,'EdgeAlpha',1,'MarkerSize',5,'Marker','diamond',...
    'Interpreter','latex',...
    'NodeFontWeight','bold',...
    'NodeFontAngle','italic',...
    'NodeFontName','Times New Roman',...
    'NodeFontSize',15,...
    'NodeLabel',[1:n],...
    'NodeColor',[0.635294117647059 0.0784313725490196 0.184313725490196],...
    'ShowArrows','on',...
    'ArrowSize',10,...
    'LineWidth',2,...
    'LineStyle','-.',...
    'EdgeFontWeight','bold',...
    'EdgeFontName','Consolas-with-Yahei',...
    'EdgeColor',[0 0 1],...
    'EdgeLabel',{},...
    'Layout',...
    'layered');

% 创建 title
title('任务调度图');

box(axes1,'on');
hold(axes1,'off');
% 设置其余坐标区属性
set(axes1,'XTick',[],'YTick',[]);
